### ISSUE TITLE
support for unix domain sockets?

### ISSUE THREAD

**Issue by bhurlow** [aleph-io/aleph#212]
looks like netty has some support for UDS: http://netty.io/4.0/api/io/netty/channel/unix/package-summary.html

@ztellman would you consider a PR for this?

**Comment by bhurlow** [comment]
this might be too platform specific or not in keeping with the goals of aleph...

**Comment by ztellman** [comment]
I've also been considering adding support for STOMP and MQTT.  I'm not sure if I'm happy with the current scope of the library, or want to add similar shims for the other protocols Netty supports.  If I do those, I think it makes sense to also add this.  Let me give it some thought.

**Comment by bhurlow** [comment]
The more manifold streams the better as far as I'm concerned. I suppose part of the question is netty support. If a different library provided those other transports I think I'd find it useful even if outside of aleph proper

**Comment by brendanyounger** [comment]
+1 for this as well. I'm happy to work on a PR for this feature (server and client), but I may need some help with Netty internals.  Right now I'm stuck on this error

```
{:type java.lang.ClassCastException
   :message "io.netty.channel.unix.DomainSocketAddress cannot be cast to java.net.InetSocketAddress"
   :at [io.netty.channel.epoll.EpollServerSocketChannel doBind "EpollServerSocketChannel.java" 89]}
```
when calling aleph.http.server/start-server with a `DomainSocketAddress` and `epoll?` set to true.  Apparently, the code for `doBind` assumes the address is an `InetSocketAddress`, but I don't know enough about ChannelPipelines to figure out what to change.

**Comment by kachayev** [comment]
Closing the issue as we have another feature request open for unix domain sockets (linked above).
