### ISSUE TITLE
Kqueue

### ISSUE THREAD

**Issue by rafacustodio** [aleph-io/aleph#330]
Netty has kqueue as transport as well http://netty.io/wiki/native-transports.html, I use mac and FreeBSD for servers, is there any plans to add kqueue here as well?

**Comment by ztellman** [comment]
It should be pretty straightforward, let me take a look at the Netty
implementation and see what I can do.

**Comment by kachayev** [comment]
Closing the issue as we have another one with KQueue feature request #526
