### ISSUE TITLE
"Connection: Keep-Alive" is redundant for HTTP/1.1

### ISSUE THREAD

**Issue by kachayev** [aleph-io/aleph#359]
Right now, "default" HTTP server

```clojure
user=> (require '[aleph.http :as http])
user=> (http/start-server (fn [_] {:status 200 :body "Pong"}) {:port 3010})
```

works like this:

```shell
$ curl -vvv http://localhost:3010/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 3010 (#0)
> GET / HTTP/1.1
> Host: localhost:3010
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: Aleph/0.4.4
< Connection: Keep-Alive <--- redundant
< Date: Tue, 20 Feb 2018 22:27:49 GMT
< content-length: 4
<
* Connection #0 to host localhost left intact
```

But due to [RFC7230](https://tools.ietf.org/html/rfc7230#section-6.3) HTTP/1.1 defaults to the persistent connections and `Connection` header might be omitted here. So my suggestion is to set it [here](https://github.com/ztellman/aleph/blob/a377fbb5953c30d473118fc81d99fcf1658cad2c/src/aleph/http/server.clj#L125) only when `keep-alive?` is set to `false`. Any thoughts, observations or objections?

**Comment by ztellman** [comment]
I vaguely recall that some clients aren’t fully compliant, and require this
to be explicit even for 1.1, but can’t give a concrete example. Let me do a
bit of research and get back to you.

**Comment by kachayev** [comment]
@ztellman Sure thing! It's not a critical issue (at least not in a classical meaning of the word "issue"). Just an observation that I wanted to discuss. I will also dig deeper into potential corner cases.
