### ISSUE TITLE
Custom 100-continue handler

### ISSUE THREAD

**Issue by kachayev** [aleph-io/aleph#462]
Right now server [includes](https://github.com/ztellman/aleph/blob/be1ee04c130660ce69ee7c6603132b36be79ec1f/src/aleph/http/server.clj#L431) default `HttpServerExpectContinueHandler` to the server pipeline, which basically [accepts](https://github.com/netty/netty/blob/00afb19d7a37de21b35ce4f6cb3fa7f74809f2ab/codec-http/src/main/java/io/netty/handler/codec/http/HttpServerExpectContinueHandler.java#L33) all expectations. If I need to implement custom logic to `expect` request processing (e.g. to check auth headers, cookies, csrf signatures etc), I have to remove this handler from the pipeline and replace it with my own `ChannelInboundHandler`. Would be nice to have some kind of `:expect-handler` (as we have for `:reject-handler` e.g.) to implement custom logic and reply with `true`, `false` or maybe even with a custom error response when necessary.

**Comment by ztellman** [comment]
I'd prefer `:continue-handler`, but otherwise this seems like a good addition.

**Comment by kachayev** [comment]
Implementation is merged.
