### ISSUE TITLE
HTTP server to send a specific file region to deal with content range requests

### ISSUE THREAD

**Issue by kachayev** [aleph-io/aleph#469]
Right now `aleph.http.core/send-file-region` internally creates an instance of `DefaultFileRegion` using `0..len` range (entire file). If I need to accept `Range` request header and reply with `HTTP/1.1 206 Partial Content`, I have to be able to specify custom offset and length params.

**Comment by kachayev** [comment]
I think we can add this functionality by introducing the following API:

```clojure
(require '[aleph.http.core :as http])
(require '[clojure.java.io :as io])

;; manually create a record
;; we can also use simple Java class instead of record?
(defn handler [req]
  {:status 200
   :body (http/PartialFileContent. (io/file filepath) 1e3 1e4)})

;; helper to construct an instance of the same record?
(defn handler [req]
  {:status 200
   :body (http/partial-file (io/file filepath) 1e3 1e4)})
```

Changes to `send-file-region` and `send-chunked-file` are quite obvious, for `ssl?` set to `true` use case we also need to construct `manifold.stream` source carefully, but that's also doable. @ztellman What do you think about API?

**Comment by ztellman** [comment]
I think I'd like to have a general `http/file` constructor that optionally takes range parameters (and defaults to the entire file), and a coercion that turns `java.io.File` (and maybe `java.nio.file.Path`?) into our internal file representation.

**Comment by kachayev** [comment]
Closing the issue as the functionality was already merged.
