### ISSUE TITLE
Hiding Server Header

### ISSUE THREAD

**Issue by tafenton** [aleph-io/aleph#512]
Hi,

Hopeful first-time contributor - issue #391 provides a means to override the server header. I'd like to omit the server header completely, but currently I'm limited to overriding it with an empty string.

I've forked the repo and added a new key, :hide-server-header?, in the options map for start-server. This passes the value (which defaults to false) through pipeline-builder, ring-handler/raw-ring-handler, handle-request, and finally send-response, where an or statement is used to ensure compatibility with the existing override approach:

`(when-not (or hide-server-header?
                        (.contains headers ^CharSequence server-name))
 ...`

I haven't been able to run the full test suite as several tests rely on "/usr/share/dict/words", but if I comment out the affected tests, I see only the same test failures as when I clone and test the current master branch.

[Fork Comparison](https://github.com/ztellman/aleph/compare/master...OriginalFenno:master)

Let me know if you're happy for me to submit a pull request!

![Testing](https://user-images.githubusercontent.com/13712300/58328508-2c642e80-7e2a-11e9-8e54-d90fe93baeff.png)

**Comment by kachayev** [comment]
I think we could solve this w/o introducing new configuration key (e.g. `:hide-server-header?`) by just removing "server" header when the value is an empty string. It might not be that obvious but the use case doesn't feel too generic. @ztellman what do you think?

**Comment by danielcompton** [comment]
Setting the `Server` header to nil seems like it could be an option to indicate that it should be removed, but I'm not sure if that conflicts with anything else?

**Comment by OriginalFenno** [comment]
Omitting the header when nil is supplied makes sense. If this is the preferred route, vs. a server option at initialisation, is there a convenient way of setting it globally? I might be missing something obvious, but the only way I've found so far is to wrap each handler with a middleware to merge in e.g. {:headers {"server" nil}}.

**Comment by kachayev** [comment]
@danielcompton `map->headers!` would prevent this from happening, [here](https://github.com/ztellman/aleph/blob/d3dc2e9835b58fb53b957171765e8da68e52aa84/src/aleph/http/core.clj#L157-L158). I don't feel that omitting a single header is a good justification to patch (or extend) this check :) 

@OriginalFenno Why "each" handler? You need to put a middleware once, right before passing it to `http/start-server`

**Comment by kachayev** [comment]
I'm closing the issue as there are multiple workarounds (e.g. `pipeline-transform` could be used to inject Netty handler to intercept `HttpRequest` object before passing it into encoder).

**Comment by rgm** [comment]
If anyone ever needs an example of how the `pipeline-transform` idea works, here's an example:

https://github.com/rgm/experiments/blob/master/2024/202405-aleph/user.clj

(thx @alexander-yakushev)
