### ISSUE TITLE
How to test websocket handlers without running a server?

### ISSUE THREAD

**Issue by sorsasampo** [aleph-io/aleph#518]
The tests in [test/aleph/websocket_test.clj](https://github.com/ztellman/aleph/blob/master/test/aleph/websocket_test.clj) all seem to set up a HTTP server.

It's pretty conventional to test ring applications without running a server, just by passing a mock request to the app routing, constructed using something like peridot or ring-mock.

How would I go about constructing a websocket mock request in tests, that would allow testing the websocket handler without running a full server?

**Comment by 7even** [comment]
It seems like you can emulate it with [`manifold.stream/splice`](https://github.com/ztellman/manifold/blob/c29df26f7316477490969976f1956a2c8594bf3f/src/manifold/stream.clj#L423) - just use it in tests instead of the value returned by `aleph.http/websocket-connection`.

In my case this code solved the problem:

``` clj
(def ws-conn
  (atom nil))

(defn with-ws [tests]
  (let [server->client (s/stream)
        client->server (s/stream)]
    (reset! ws-conn
            (s/splice server->client
                      client->server))
    (tests)
    (s/close! @ws-conn)
    (reset! ws-conn nil)))

;; then in the test namespace
(use-fixtures :each with-ws)

;; then pass @ws-conn to the websocket handler function and test by:
;; sending to WS
(s/put! (.source @ws-conn) :data)
;; and reading from WS
(s/take! (.sink @ws-conn))
```

**Comment by kachayev** [comment]
Closing the issue. @sorsasampo, if you have more question or need more detailed example, feel free to re-open.
