### ISSUE TITLE
Doubled query string in HTTP request via proxy

### ISSUE THREAD

**Issue by flodiebold** [aleph-io/aleph#524]
Making a request with an URL containing a query string, i.e. something like `{:url "http://foo.com/?a=b"}` while using an HTTP proxy results in the query string being appended to the URL again, i.e. `"http://foo.com/?a=b?a=b"`. I think this is because `:request-url` is used as the `:uri` [here](https://github.com/ztellman/aleph/blob/d3dc2e9835b58fb53b957171765e8da68e52aa84/src/aleph/http/client.clj#L507), but _also_ the `:query-string` extracted by the middleware is kept (and then appended again).

**Comment by danielcompton** [comment]
Can you post a minimal reproduction of this, including which Aleph version you are using?

**Comment by flodiebold** [comment]
```clojure
aleph.http> (def _pool (aleph.http/connection-pool {:connection-options {:proxy-options {:host "localhost" :port 10000}}}))
#'aleph.http/_pool
aleph.http> (-> (aleph.http/request {:method :get :url "http://httpbin.org/get?foo=bar" :pool _pool}) deref :body byte-streams/to-string)
"{\n  \"args\": {\n    \"foo\": \"bar?foo=bar\"\n  }, \n  \"headers\": {\n    \"Content-Length\": \"0\", \n    \"Forwarded\": \"by=\\\"[::ffff:127.0.0.1]\\\"; for=\\\"[::ffff:127.0.0.1]\\\"; proto=http; host=httpbin.org\", \n    \"Host\": \"httpbin.org\", \n    \"X-Amzn-Trace-Id\": \"Root=1-5f0328f8-644479e0f99a0d502bdcfb20\"\n  }, \n  \"origin\": \"35.205.2.61\", \n  \"url\": \"http://httpbin.org/get?foo=bar%3Ffoo=bar\"\n}\n"
```
This is with current aleph (0.4.6), with an HTTP proxy running on `localhost:10000` of course. (I've checked with Wireshark that the request already goes to the proxy like this, so it shouldn't even be necessary to have a proxy to reproduce this.)
