### ISSUE TITLE
Websockets heartbeat handler throws NPE if no timeout specified.

### ISSUE THREAD

**Issue by wardle** [aleph-io/aleph#552]
Fixed in linked pull request. If 'timeout' property of heartbeats configuration is truly optional, then timeout can be nil, and clojure's pos? throws an NPE. #551

**Comment by kachayev** [comment]
Good catch. Thanks a lot!

**Comment by kachayev** [comment]
#551 is merged. Thanks!

**Comment by wardle** [comment]
Thanks - and many thanks indeed for all of your hard work on this - cc @ztellman - it's really excellent.
